steps:
  # 1. Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA', 
      '.'
    ]

  # 2. 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
    ]

  # 3. Cloud Run 배포 (내부 HTTP Load Balancer 연동 전제)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--set-env-vars'
      - 'BUCKET_NAME=${_BUCKET_NAME}'
      - '--service-account'
      - '${_SERVICE_ACCOUNT_EMAIL}'
      # 내부 HTTP Load Balancer를 통해서만 접근하는 구성
      - '--ingress=internal-and-cloud-load-balancing'
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'

substitutions:
  _SERVICE_NAME: 'crs-gcs-filedownload-page-iap'
  _REGION: 'asia-northeast3'
  _REPO_NAME: 'cloud-run-source-deploy'
  _IMAGE_NAME: 'gcs-filedownload-page-iap/crs-gcs-filedownload-page-iap'
  _BUCKET_NAME: 'gcp-in-ca-test-bucket-wocheon07'
  _SERVICE_ACCOUNT_EMAIL: 'gcs-manage-sa@gcp-in-ca.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
