steps:
  # 1. Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/[REPOSITORY_NAME]/[IMAGE_NAME]:$COMMIT_SHA', '.']

  # 2. Artifact Registry에 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/[REPOSITORY_NAME]/[IMAGE_NAME]:$COMMIT_SHA']

  # 3. Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '[SERVICE_NAME]'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/[REPOSITORY_NAME]/[IMAGE_NAME]:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--set-env-vars'
      - 'BUCKET_NAME=[YOUR_BUCKET_NAME]'
      - '--platform'
      - 'managed'

images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/[REPOSITORY_NAME]/[IMAGE_NAME]:$COMMIT_SHA'